### ISSUE TITLE
Subsplit support, for LiveSplit

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#122]

**Comment by CryZe** [comment]
Subsplits won't stay this way btw. They'll use "Split Configurations" soon which are basically component settings stored in splits. But I guess you can support the dashes too if you want to.

**Comment by glacials** [comment]
Alright, thanks for the heads up. I'll wait until the format changes before doing anything then.

**Comment by BatedUrGonnaDie** [comment]
Closed by #617
