### ISSUE TITLE
API run ids should be the base 36 id

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#130]
External developers should never have to deal with the base 10 ids, it's weird having two methods of identifying a run.

**Comment by CryZe** [comment]
Nice, that's good. I think somewhere in LiveSplit we literally have to do 2 calls, cause the id is in the wrong base, so that would be a good change :+1: 

Oh yeah, I found it, it's here: https://github.com/LiveSplit/LiveSplit/blob/master/LiveSplit/LiveSplit.Core/Web/Share/SplitsIO.cs#L169

**Comment by glacials** [comment]
These are implemented in v4 (which isn't ready yet, but this issue no longer represents independent work)
