### ISSUE TITLE
Split times over 24 hours are not recorded/displayed properly

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#131]
See: https://splits.io/3i5

My final split time was over 24 hours but it shows the final split time as that of the penultimate split due to the fact that LiveSplit stores split times over 24 hours as number of days (i.e. 24:36:02.48 == 1.00:36:02.48 in LS).

**Comment by glacials** [comment]
Haha, interesting bug. Should be an easy fix.

**Comment by jeffreyhobson** [comment]
FYI, something similar to this is still happening in the "Export to Twitch Panel" feature, except it replaces the 24 hours with a 0 instead of pulling from the previous split.

**Comment by glacials** [comment]
Okay, I'll reopen and look at this when I can.

**Comment by BatedUrGonnaDie** [comment]
This looks like its fixed in both places.
