### ISSUE TITLE
Rollbar -> GitHub issues, show on 500 page

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#133]
I want to see if it's easy / possible to have every error 500 page directly link to a GitHub issue created to represent that issue. The error -> GitHub issue part can be done through rollbar, which we already use for errors. Not sure about the direct linking to that issue part.

**Comment by Nightfirecat** [comment]
Might want to be careful not to cause issue spammage if the same page (or pages of similar structure) are visited often or repeatedly.

**Comment by glacials** [comment]
Should've explained this in the description, but Rollbar groups error occurrences by the actual name of the error/exception in Ruby, so one bug that translates to 1000 pageviews of a 500 would still be represented as one GitHub issue. I don't think it'd be *too* spammy, but you're right either way that it's something to take into consideration.

(To give you an idea, Rollbar's been hooked up for about four months and there've been 185 distinct errors recognized among 1813 error occurrences.)

**Comment by Nightfirecat** [comment]
Ok, cool.

**Comment by glacials** [comment]
Decided against this for now.
