### ISSUE TITLE
API v3 doesn't have working pagination

### ISSUE THREAD

**Issue by CryZe** [glacials/splits-io#154]
The documentation claims that there's pagination, but there's no pagination information to be found in any API responses.

Here's an example of where there should be pagination information in the response according to the documentation:
https://splits.io/api/v3/games/15/categories/55/runs

**Comment by CryZe** [comment]
Apparently it also completely ignores the ?page=2 when given.

**Comment by glacials** [comment]
I cannot reproduce -- are you looking in the headers? Here's what a request/response should look like (and what I'm currently getting).

```bash
curl -i https://splits.io/api/v3/games/15/categories/55/runs
```

```bash
HTTP/1.1 200 OK
Server: cloudflare-nginx
...
Link: <https://splits.io/api/v3/games/15/categories/55/runs?page=1>; rel="first", <https://splits.io/api/v3/games/15/categories/55/runs?page=1>; rel="prev", <https://splits.io/api/v3/games/15/categories/55/runs?page=3>; rel="last", <https://splits.io/api/v3/games/15/categories/55/runs?page=3>; rel="next"
Total: 55
Per-Page: 20
...

{
  "runs": [
      "id": 4062,
      "path": "/34u",
      "name": "Super Mario Sunshine 120 Shines",
      "program": "livesplit",
...
```

As for ignoring `?page=2`, can you paste me the full responses you get from both of these hits? I'm correctly getting a different set of runs between the two.

**Comment by CryZe** [comment]
Oh, nvm then, I was looking for it in the JSON response.

**Comment by CryZe** [comment]
The documentation should probably state that it's in the "HTTP headers" ("headers" made me think it was in the upper level of the JSON response).

**Comment by glacials** [comment]
Done :)
