### ISSUE TITLE
ShitSplit Support

### ISSUE THREAD

**Issue by CryZe** [glacials/splits-io#163]
ShitSplit is a timer that is mostly used for timing Manual Game Time like Punch Out and the Sonic Games. It doesn't even have a timer because of that. LiveSplit can parse it, so maybe splits i/o should be able to parse it too. I don't have any splits for ShitSplit atm, but you can look at how LiveSplit parses it:
https://github.com/LiveSplit/LiveSplit/blob/master/LiveSplit/LiveSplit.Core/Model/RunFactories/ShitSplitRunFactory.cs#L17-L50

**Comment by CryZe** [comment]
Also it has Subsplits built-in. I don't think it stores actual times for the subsplits though, just for the major splits.

**Comment by glacials** [comment]
Cool, I've been changing how we store splits with realtime vs. gametime in mind, this will fit nicely into that as a gametime-only timer.

**Comment by BatedUrGonnaDie** [comment]
Closed with #312
