### ISSUE TITLE
Allow unencrypted readonly access to the API v3

### ISSUE THREAD

**Issue by sgt-kabukiman** [glacials/splits-io#169]
As of now, the splits.io API (at least in v3) requires HTTPS when accessing it. While that makes total sense and has my full support, it kind of shot us in the knee.

Our project runs on Debian Squeeze and is using PHP 5.3 (with the option of at least upgrading to 5.4). Unfortunately, the packaged openssl version for squeeze (0.9.8o-squeeze20 for squeeze-lts) is not able to handle CloudFlare's SSL settings, especially the allowed cipher suites (openssl 0.9.8 does not yet know how to handle EC-based ciphers on a SHA2-based certificate). Hence we cannot make successful requests to the splits.io API *at all*. We'd either have to go with a full dist upgrade or compile openssl ourselves -- both options are out of the question at the moment :-/

For our usecase, having an unauthenticated, readonly access to the split data is enough, which is why I'd like to ask that you lift the requirement for HTTPS for readonly access. I'm on the "HTTPS all the things!" side myself, which is why I'm having a hard time asking you to reduce your site's security. :-/

For now, we use a reverse proxy via another server, but that's a pretty ugly temporary solution.

I'm sorry.

**Comment by glacials** [comment]
Sorry man, I understand your situation -- I've been in similar ones -- but I'm afraid I am definitely against this. Whether or not requests are creating or editing any information, I strongly believe that HTTPS should be strictly enforced. You're welcome to cache as much as you want on your proxy server and continue using that over HTTP, but splits.io is going to stay HTTPS.

What sort of control do you guys have over your machine(s)? If you can't change anything serverside, perhaps you could retrieve and display the splits in JS.

[1]: https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure
[2]: https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/

**Comment by sgt-kabukiman** [comment]
I can see your point and didn't really have much hope anyway ;-) For now, we'll stick with the proxy.
