### ISSUE TITLE
Parse LiveSplit 1.6 Splits

### ISSUE THREAD

**Issue by CryZe** [glacials/splits-io#171]
In LiveSplit 1.6, the Run History is renamed to Attempt History and the <Time /> Elements in there are renamed to <Attempt /> and optionally support 2 UTC time stamps attributes called "started" and "ended" that store when attempts were started and when they ended. Obviously old attempts from 1.5 or earlier don't have these, that's why they are optional. The file format might change a bit until 1.6 releases since we want to implement Split Configurations (per splits file component settings), but that will most likely just be a new tag and will neither need to be parsed by you guys nor does it change anything else in the file format. The file format version is now 1.5.0 instead of 1.4.2

Here's one example file: http://puu.sh/hXrZk.lss

**Comment by glacials** [comment]
I'll get to work on this. Are lss file versions now officially divergent from LiveSplit version? If so I'll just change my code a bit to follow that pattern.

**Comment by CryZe** [comment]
It was like that before too. 1.5 and 1.4 both used LSS version 1.4.2 I think.

**Comment by glacials** [comment]
Yeah, I wasn't sure if that only was because the format didn't change from LiveSplit 1.4 to 1.5, so there was no need to bump version. Just want to make sure I understand correctly that they're separate now.

**Comment by CryZe** [comment]
Yeah, just to make sure, I checked again: 
![Line Log of XMLRunSaver](http://puu.sh/hYNmG.png)

**Comment by glacials** [comment]
Okay, added 1.5 support in c290a508649c09ffcfad00361e401384c10e04cf. Here are those AHIT splits: https://splits.io/56r

Can you guys make sure everything works from your end as you expect? Then we can close the issue.

**Comment by CryZe** [comment]
Nice, looks like it works. That was fast :+1:
