### ISSUE TITLE
/users/:user_id/runs 500's for some users

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [glacials/splits-io#173]
https://splits.io/api/v3/users/glacials/runs Broken
https://splits.io/api/v3/users/batedurgonnadie/runs Works
Same behavior with users/:user_id/pbs

**Comment by glacials** [comment]
This was happening for responses containing runs belonging to a category with a `nil` game. Updated ActiveModel::Serializers to a version that serializes `nil` as `null` without trying to treat it like a game, should be fixed.

**Comment by BatedUrGonnaDie** [comment]
That's what I thought the problem was, but wasn't completely sure.  Thanks
