### ISSUE TITLE
v3 API break

### ISSUE THREAD

**Issue by sgt-kabukiman** [glacials/splits-io#175]
We just noticed that the API no longer returns a ``run`` root element for responses like https://splits.io/api/v3/runs/4q3. Compare with the documented structure at https://github.com/glacials/splits-io/blob/master/docs/api.md#example-response-10.

**Comment by glacials** [comment]
Thanks, I'll fix this right away. Must be an effect of some of the ActiveModel::Serializer upgrade stuff I've been doing.

I'll also write some tests to catch this sort of stuff.

**Comment by sgt-kabukiman** [comment]
Thanks!
