### ISSUE TITLE
API issues

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [glacials/splits-io#177]
/users/:user_id/runs Missing root node of "runs"
It also appears that all the game fields are "null" ex: https://splits.io/api/v3/users/batedurgonnadie/pbs
Game field missing from some runs. ex: https://splits.io/api/v3/runs/5h9
API docs say user can be base 10 Twitch ID

**Comment by glacials** [comment]
Looks like the api docs say twitch usernames or base 10 splits-io id, not seeing anything about Twitch id.

Rest of the stuff is bugs, fix going out shortly. All of them are stupid mistakes from earlier fixes today, i'm writing tests right now so i can prevent myself from doing this.

**Comment by BatedUrGonnaDie** [comment]
Yeah, last one was my bad.  I combined Twitch username with splits-io id.
