### ISSUE TITLE
LiveSplit 1.6's Attempt History is parsed wrong

### ISSUE THREAD

**Issue by CryZe** [glacials/splits-io#201]
The Attempt History contains Attempt Nodes instead of Time Nodes, which you seem to be parsing right now (according to the code). Attempt Nodes have additional started, ended, isStartedSynced and isEndedSynced attributes. The started and ended attributes are basically UTC time stamps that store when the attempt started and ended (even resets). The isSynced attributes store whether these are actual Atomic Clock Time Stamps or just based off the Windows Clock. Also those attributes might not necessarily be available for Attempts of older versions of LiveSplit for example. 

Here's LiveSplit's code that creates these Nodes: https://github.com/LiveSplit/LiveSplit/blob/master/LiveSplit/LiveSplit.Core/Model/Attempt.cs#L45

**Comment by glacials** [comment]
Thanks! Should be fixed now. Out of curiosity, what is the purpose for syncing start/end times? How different are they from people's computers?

**Comment by CryZe** [comment]
Well, the PC's clock might be out of sync with an atomic clock. Dalet's Run Highlighter can automatically highlight runs in the history and needs to make sure those time stamps are correct in order for him to properly find the right time stamp in the right recording on Twitch.

**Comment by glacials** [comment]
Okay, I was under the impression that Windows auto synced its clock to Microsoft's time servers. Even with this, local clocks aren't accurate enough?

**Comment by CryZe** [comment]
They definitely are not accurate enough. CaracarnVi's PC Clock is off by more than 10 seconds after just 1.5 hours already for example.

**Comment by glacials** [comment]
Ah okay, dang that's quite a bit. Thanks for explaining :smile_cat:
