### ISSUE TITLE
Game list

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#203]
https://splits.io/games should display a list of games which have shortnames along with the search bar.

Options:
- Dropdown menu, similar to the one on the run edit page
- Series of pages keyed by first letter (one page for games that begin with "A", one for "B", etc.) and displayed alphabetically within each page
- Series of pages with some constant amount of games per page, and page counter at the bottom (I don't like this)

Might also be nice to support some custom ordering, e.g. by most recent run upload or most runs uploaded or most runs uploaded recently, but not required for now.

**Comment by BatedUrGonnaDie** [comment]
Closed by #540
