### ISSUE TITLE
How is game association made

### ISSUE THREAD

**Issue by MCMic** [glacials/splits-io#205]
Can you explain in the FAQ how splits get associated to games?
I tried setting the exact same name «Ninja Gaiden II: The Dark Sword of Chaos Any%» in llanfair and my splits are still not linked to the corresponding game.
Anything I can do or is that a missing feature when loading llanfair splits?

**Comment by MCMic** [comment]
Ok, found a way to edit associated game if I sign in. It should still be explained in the faq though.

**Comment by glacials** [comment]
Yeah we only try to pick up game/category from timers that have distinct fields for them, which is only LiveSplit right now. I'll update the faq to explain this. Also made #206 for trying to guess game and category better from other timers.

Thanks!
