### ISSUE TITLE
Add Ability to Report / Request to Remove Obviously Impossible Times

### ISSUE THREAD

**Issue by mkoch227** [glacials/splits-io#208]
Looking at some of the Super Mario 64 16-star splits, there are several 00:00:00 times, which are obviously impossible to complete.  It would be nice if there was a way to report / request to remove these to keep data clean.
![screen shot 2016-01-21 at 8 59 08 pm](https://cloud.githubusercontent.com/assets/333430/12500530/037580be-c082-11e5-9735-7bb3efd252ca.png)

**Comment by glacials** [comment]
Hi! Most of the time, blank splits aren't uploaded maliciously or accidentally; people just want to make their routes available without including their actual PB splits. So I don't think the right answer is to remove them, but I do understand that they clog search results like hell.

I think the proper fix is to address #67 (separate routes from runs), but it's a bit of a project. For now I went ahead and deployed a quick fix that removes blank splits from search results and game/category pages.

This doesn't fix the problem if the uploaded splits aren't blank (e.g. the `00:00:03` in your screenshot), but it should fix the other 99%. If this solves your root concern you can close this issue. If it does not and you still strongly believe a report function should exist, you can leave it open.

Thank you for reporting :)

**Comment by mkoch227** [comment]
I honestly never thought of uploading empty splits as routes, but it does make sense.  Anyways, this does address the root concern in my opinion, as the search results do look cleaner now.  Thanks :smile:.
