### ISSUE TITLE
Delete/disown menu on frontpage looks weird

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#214]
![screenshot 2016-02-09 11 36 49](https://cloud.githubusercontent.com/assets/438911/12928289/6d6ace5e-cf21-11e5-88d3-254f96303a9d.png)

**Comment by jhobz** [comment]
Whoops, sorry from the dupe. Initial investigation shows it might be from squashing two anchor tags into one list item and making them behave as list items instead of using two list items.

**Comment by jhobz** [comment]
I was wrong, the culprit is:
```css
.dropdown-menu {
    /* right: 0; */
}
```

The dropdown could definitely use a border too though. Potentially one between the options as well.
