### ISSUE TITLE
Dropdown text is hard to read on convert page in darkmode

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#219]
![image](https://cloud.githubusercontent.com/assets/1765799/13767816/35314380-ea45-11e5-843f-a30ad99d9643.png)

Should be a simple `background-color` fix on the `<select>`.

**Comment by glacials** [comment]
Cool, agreed should be easy. I think this is a symptom of a bigger problem of darkmode being a second-class citizen though. It's hard to remember to write stuff in a way that doesn't break it. Will make a new issue for that though, this fix is simple.

**Comment by glacials** [comment]
Fixed by 735dba58adaf7861509218d23d21c1d67294834d
