### ISSUE TITLE
Navigating away from, then back to, a run page breaks timeline hovers

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#224]
1. Go to https://splits.io/ik7 or any run page
  * Ensure timeline hovering works (showing segment details when hovering over the segment)
2. Soft-navigate away, e.g. by clicking the game title
3. Press the back button in your browser
  * Expected: timeline hovering still works
  * Actual: It doesn't

**Comment by jhobz** [comment]
Note: Clicking on "stats" breaks the timeline for the stats page, but the timeline works again once you navigate back.

**Comment by glacials** [comment]
Both should be fixed.
