### ISSUE TITLE
Pagination in search results appears to be broken for games that are not tied to SRL ids

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#226]
Repro steps:
1. Go to https://splits.io/games?q=kingdom+hearts+hd+1.5
2. Try to use the pagination controls for either block of runs (I recommend clicking a few different controls to see the different results).

As an aside, the results screen is a bit unclear when multiple games show up. In the link above, two games are shown at the top, but then there is a "Runs" section with two subsections that each have individual pagination with no titles. I'm assuming they correspond to the two games at the top, but it could probably be clearer via subtitles or something. I can split that into a separate issue if you want.

**Comment by glacials** [comment]
I didn't bother finding the root cause but I imagine it was an artifact of powering multiple lists with one set of pagination parameters, which is awkward so I ditched it. All runs are in one table now.

Can you confirm that this is fixed?
