### ISSUE TITLE
CORS issue using Fetch API

### ISSUE THREAD

**Issue by bryanveloso** [glacials/splits-io#240]
Been trying to fetch some runs from my React application, and I'm getting the following error:

> Fetch API cannot load https://splits.io/api/v3/users/avalonstar/runs/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Obviously the URL doesn't 404. [After doing some research](http://stackoverflow.com/a/33662315) it seems that Chrome (using the default Fetch API) sends out a "pre-flight" OPTIONS method that isn't handled. That said, I see that OPTIONS is defined here: https://github.com/glacials/splits-io/blob/master/app/controllers/api/v2/application_controller.rb#L43-L48, but that may not be seen during pre-flight... so I'm not sure what's going on.

😨

**Comment by bryanveloso** [comment]
Found this as well: http://stackoverflow.com/questions/20819196/rails-responds-with-404-on-cors-preflight-options-request

**Comment by glacials** [comment]
So the situation looks like:

1. Browser needs to send OPTIONS preflight and inspect CORS headers to see if it's allowed to send an actual request.
2. We have the CORS headers on all API routes, but we don't have routes for OPTIONS requests, so we 404. 
3. Browser cries.

I think I've fixed this with b75d86126204dbdfb423a07c7726f17b36b8cb0d, which just responds to all OPTIONS requests for `/api/v3/*` and `/api/v4/*` with "yeah you're good", but I couldn't actually reproduce the issue from my browser console. Can you verify?

**Comment by jhobz** [comment]
Just a quick note that I've found [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj) to often be an extremely useful extension whenever you need to do some header spoofing.

**Comment by bryanveloso** [comment]
@glacials — Yep, that fixed it for me. :D
@jhobz — Thanks for the tools!
