### ISSUE TITLE
Clicking on a friend's game should take you to that friend's PB for that game

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#245]
e.g.:

<img width="196" alt="screenshot 2016-08-09 09 10 51" src="https://cloud.githubusercontent.com/assets/438911/17523920/32b4d35c-5e11-11e6-8f3f-f893885df615.png">

Clicking "refunct" takes me to `/games/refunct` but I wanted to see bated's Refunct PB.

**Comment by BatedUrGonnaDie** [comment]
What if the the user has multiple pb's for that game under the different categories?

**Comment by glacials** [comment]
Good point. Options:

1. Start listing all categories they run as well, and linkify those instead 
2. Make a new page type that features a runner-game pairing, listing their PBs for that game, and link the game text to that
3. Link the game text to just one of the several categories they run, chosen by most recently run or something 
4. Forget about the whole thing and leave as-is

I like option 2, as we could show PB times for each category in nice big numbers, and even show some interesting category-nonspecific stats like total playtime (#185) and some guess at overall game skill level. That's a pretty tall order but I think it would be cool

**Comment by BatedUrGonnaDie** [comment]
I agree that option 2 sounds the best.  The current way is a bit weird I expected it to take me to that person's run but after clicking it once what it does is clear.
Listing the categories among the games seems like it will get out of hand quickly, especially seeing as how you can define new categories at will.
I also like the idea for game specific stats about a runner.  Numbers are always cool to look at and you could have something to compare against other people.

**Comment by glacials** [comment]
Closing as the frontpage follows section has been redone to be a list of follows' recent PBs, so this is no longer an issue.
