### ISSUE TITLE
v4 api not working as documented

### ISSUE THREAD

**Issue by moskvax** [glacials/splits-io#249]
A few of the endpoints documented in the v4 api currently seem not to work (using parameters which should return data and do so in v3 and in the browser):
- `games/:game/runners` returns 404
- `runners/:runner` returns 404
- `categories/:category` and all of its routes return 204

**Comment by glacials** [comment]
v4 is still under development, I recommend using v3 for now. I'll add a note to the v4 docs saying they're not ready yet. I'll also leave this issue open because it still applies :p
