### ISSUE TITLE
category tabs on game page not working

### ISSUE THREAD

**Issue by moskvax** [glacials/splits-io#250]
On https://splits.io/games/tww for example, currently the category "Any% No Tuner" is selected by default. Trying to change category by clicking a different tab shows the loading UI and changes the URL displayed in the browser but doesn't change the active tab or show a different list of runs. I've noticed this problem doesn't happen when viewing sum of best leaderboards, where switching tabs does what you expect.

**Comment by glacials** [comment]
Thanks, I've got a fix!
