### ISSUE TITLE
Stats graphs need dark mode styles

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#255]
Just the text is probably minimum, although the graph lines would be nice as well.

![image](https://cloud.githubusercontent.com/assets/1765799/19463722/6c7bd66e-94c4-11e6-8aea-60df18a334f3.png)

**Comment by glacials** [comment]
Thanks, +1 reason for #221.

**Comment by jhobz** [comment]
Tooltips will probably need to be updated with #221 as well:
![image](https://cloud.githubusercontent.com/assets/1765799/19499681/b1dd660e-9565-11e6-89a8-8adbebf74c69.png)

**Comment by BatedUrGonnaDie** [comment]
Should be fixed with permadarkmode.
