### ISSUE TITLE
SRDC auto-embed broken

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#256]
Most likely the same cause as #254, auto-embed of splits on speedrun.com has broken.

![image](https://cloud.githubusercontent.com/assets/1765799/19465759/67c222f8-94d4-11e6-96af-b893d1cf7c1b.png)

**Comment by jhobz** [comment]
This applies to both new submissions and existing runs.

**Comment by BatedUrGonnaDie** [comment]
It might be related to api v2 being removed as well.

**Comment by glacials** [comment]
Nah according to #169 they seem to be using v3. ID lookups are broken in v3 apparently (expecting base 10 rather than base 36). Fix incoming, and I'm also going to use this opportunity to set up CI that blocks deploys if tests fail.
