### ISSUE TITLE
Can only upload RTA times?

### ISSUE THREAD

**Issue by Ulti-FD** [glacials/splits-io#261]
The run I'd like to upload uses LiveSplit under Game Time format, but no matter what I do the site only wants to read the RTA section of the file (even if the RTA section is empty and the SS section has complete splits). Yes, the .lss is already associated with the "SS" catagory, so that isn't the problem.

**Comment by glacials** [comment]
The ability to parse game times has not been written (see #146). Thanks for letting me know, frankly there hasn't really been any demand so I haven't given this any thought in quite a while. Can I ask what game/community you're in that uses game time?

**Comment by Ulti-FD** [comment]
It's for a Quake [1] marathon run. Thanks for the reply, hope this can get sorted out soon.

**Comment by bepstein111** [comment]
The Dishonored 1 community would also like to see Game Time parsing implemented. Hope we can work something out soon.

**Comment by 7imekeeper** [comment]
I'd like game time as well. Medal of Honor: Airborne uses it since load times are non-zero and very inconsistent even on an SSD.

**Comment by glacials** [comment]
Thanks for all the input everyone, I've recently completed some database groundwork that supports this, and will be adding game time as my next big project.
