### ISSUE TITLE
Darkmode link should probably switch to "lightmode" once in darkmode

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#264]
![image](https://cloud.githubusercontent.com/assets/1765799/21071891/95703082-be7d-11e6-8428-ab220a1e40ac.png)

Once in dark mode, the text should probably switch to "lightmode" to indicate it will switch back if you click on it (even though that's probably already the assumed function).

**Comment by glacials** [comment]
Done, thanks!
