### ISSUE TITLE
Show Split Icons

### ISSUE THREAD

**Issue by CryZe** [glacials/splits-io#267]
While implementing LiveSplit One we tried to decode LiveSplit's weird serialized image format and it turns out that the decoding logic is super easy to implement.

First you take the base64-encoded data and decode it. You then take the data starting from offset 0xA1 to the end (except the very last byte). And that's the original image in it's original file format (so PNG, GIF, JPEG or whatever). In LiveSplit One we then encode it into a data url so we can just embed it easily.

Here's LiveSplit One's code that does this:

[livesplit_core::parser::lss::image](https://github.com/CryZe/livesplit-core/blob/6fb652973d773604f4dc23605ab3a383af76fd3d/src/parser/lss.rs#L165)

Also due to the nature of base64, every 3 bytes are encoded as 4 characters, so you can cut away a multiple of 4 characters safely, before decoding the base64. So it turns out you can cut away 212 characters, decode it and then cut away 2 bytes at the beginning and 1 at the end:

[livesplit_core::parser::lss::image improved](https://github.com/CryZe/livesplit-core/blob/5c654813e104fe3db0529d3fbb3e21c07306fd89/src/parser/lss.rs#L173)

**Comment by glacials** [comment]
What is LiveSplit One

**Comment by CryZe** [comment]
It's a multiplatform version of LiveSplit. The core is written as a portable Rust library (original LiveSplit might use this eventually too). The frontend uses TypeScript + React (+ Electron). The Rust core is also compiled to JavaScript (WebAssembly in the future), so the whole thing runs in the browser as well without any plugins :)

![https://puu.sh/tbykX.png](https://puu.sh/tbykX.png)

**Comment by BatedUrGonnaDie** [comment]
This was added with #613 .  To show in your splits to a reparse from the edit page.

**Comment by CryZe** [comment]
That did not seem to work: https://splits.io/4cg

**Comment by BatedUrGonnaDie** [comment]
It seems to be a bit tempermental, I was having problems with it in beta but when it got to live it was working.  The problem is that I have no issues with it in dev, it's only when moving to prod that it fails to load the icons.
