### ISSUE TITLE
Open with LiveSplit One

### ISSUE THREAD

**Issue by CryZe** [glacials/splits-io#270]
Seems like a cool idea to directly open splits with LiveSplit One by just pressing a button.   
We already have a way to do this: 

https://cryze.github.io/LiveSplitOne/#/splits-io/fgh

**Comment by glacials** [comment]
Cool! I love this. LiveSplit One opens up a lot of cool feature ideas in my head for collaboration, I'd love to spitball more stuff.

**Comment by CryZe** [comment]
Something that I think may be worth exploring is using livesplit-core for parsing. As you saw it is meant to be used as a general library that can be used in any speedrunning related app and is quite easy to integrate from any language. The advantage would be that splits i/o would then be able to parse a lot more formats (we already fully support: LiveSplit, WSplit, SplitterZ, ShitSplit, Urn, Splitty, Time Split Tracker, Portal 2 Live Timer, FaceSplit, Llanfair, Gered's Llanfair Fork, Llanfair 2) and they wouldn't have to be maintained by splits i/o anymore, so just updating the library updates all the file formats too. But most importantly, I saw on Patreon that most of splits i/o's server time is spent on parsing, and since livesplit-core is written as highly-efficient native code without garbage collection, parsing time should shrink a lot and thus potentially the need to run two server instances or more, may not be necessary anymore. However while the Rust API supports all this, the C API isn't quite there yet. But if you want to try this, I'd definitely make sure the C API supports this use case in the best way possible.

**Comment by glacials** [comment]
Cool, yeah I'd love to look into this more. Is [this][1] the repo you're referring to? If so can you add build instructions so I can play around with it a bit?

[1]: https://github.com/CryZe/livesplit-core

**Comment by CryZe** [comment]
Yeah, that's the repo. It's pretty easy to build. You basically just need to set up a Rust compiler [rustup.rs](https://rustup.rs/) and then you can go into the capi folder and build it with `cargo build --release`. cargo is Rust's package manager that manages the dependencies and also calls the compiler automatically for you. After it compiled, there should be a `target/release` folder with the library compiled as a static library (usually *.a) and a shared library (usually *.so or *.dll).

You probably want to use the shared library with Ruby. I can't tell you how that works as I've never worked with Ruby, but Google probably has the answer. The functions provided by the shared library are the functions marked with `#[no_mangle]` in here: https://github.com/CryZe/livesplit-core/blob/master/capi/src/lib.rs#L66

You probably need to specify these function signatures in Ruby somehow ("low level bindings"), which looks like this in the following languages:

 - C: https://gist.github.com/CryZe/d02198caf50be10fc27c05a93b253665#file-livesplit_core-h-L8
- C#: https://github.com/CryZe/LiveSplitOneSharp/blob/master/LiveSplitOneSharp/LiveSplitCoreNative.cs#L12
- JavaScript: https://github.com/CryZe/LiveSplitOne/blob/master/src/livesplit.ts#L4

You probably want to use the `Run_parse` function, which requires you to specify a pointer to the file's data and the length in bytes. In [C#](https://github.com/CryZe/LiveSplitOneSharp/blob/master/LiveSplitOneSharp/LiveSplitCoreNative.cs#L172) this meant that I needed to manually allocate a buffer with the correct length and later manually deallocate it again. It'll probably be similar in Ruby.

The function then returns a handle to the Run. You need to check if the handle is a null pointer. A null pointer indicates that the run could not be parsed. If it's not a null pointer however, it is a valid Run that got parsed properly. You need to make sure to manually clean up this handle when you are done with it, otherwise it stays allocated (no need to deallocate the null pointer though). At the moment, there's no way to do that, since creating a Timer out of the Run does that automatically when deallocating the timer, but since you don't want to build a timer, there's no way to do that at the moment. There'll be a `Run_drop` function that'll do that. Also like I said, the C API is mostly for writing a timer at the moment, so you can't actually get any information out of the Run object. I'll extend the C API later today, so it contains functions for navigating the Run object and getting all the information out of it.

**Comment by CryZe** [comment]
Alright, I extended the C API a lot, also I added a binding generator that generates JavaScript, C# and a C Header for the C API now. This can be extended to Ruby then. So it should be possible for this to be used by splits i/o now. There may be a few functions missing, but I mostly covered everything you'd need. You need today's nightly compiler or newer. They fixed a "bug" for me, so I'm relying on this new behavior now.

**Comment by CryZe** [comment]
I've written a little parser in C#. The Ruby Parser would look pretty similar to this:

```csharp
using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using static LiveSplitCore.LiveSplitCoreNative;
using static System.Console;

namespace ParseWithLSCore
{
    class Program
    {
        static void Main(string[] args)
        {
            var file = File.ReadAllText(@"D:\Desktop\LiveSplit\Splits\Cronikeys_1.4_Splits.lss");
            var run = useString(file, (p, l) => Run_parse(p, l));

            if (run == IntPtr.Zero)
            {
                return;
            }

            WriteLine($"Game: {Run_game_name(run)}");
            WriteLine($"Category: {Run_category_name(run)}");
            WriteLine($"Attempts: {Run_attempt_count(run)}");

            var len = (int)Run_len(run);
            for (int i = 0; i < len; ++i)
            {
                var segment = Run_segment(run, (IntPtr)i);
                var name = Segment_name(segment).ToString();
                var time = Segment_personal_best_split_time(segment);
                var pb_time = "-";
                var time_span = Time_real_time(time);
                if (time_span != IntPtr.Zero)
                {
                    pb_time = TimeSpan.FromSeconds(TimeSpan_total_seconds(time_span)).ToString();
                }
                WriteLine($"{name} {pb_time}");
            }

            Run_drop(run);
        }

        private static T useString<T>(string data, Func<IntPtr, IntPtr, T> f)
        {
            var bytes = Encoding.UTF8.GetBytes(data);
            IntPtr pnt = Marshal.AllocHGlobal(bytes.Length);
            try
            {
                Marshal.Copy(bytes, 0, pnt, bytes.Length);
                return f(pnt, (IntPtr)bytes.Length);
            }
            finally
            {
                Marshal.FreeHGlobal(pnt);
            }
        }
    }
}

```

**Comment by glacials** [comment]
Thank you for all the work and examples! 👍  I highly suggest you put at least the build instructions and examples that you wrote here in the readme for livesplit-core :)
