### ISSUE TITLE
Use livesplit-core for Parsing

### ISSUE THREAD

**Issue by CryZe** [glacials/splits-io#277]
Continuing from our discussion at https://github.com/glacials/splits-io/issues/270

There are builds available in our repository for 23 common platforms, as both shared and static library and with the Ruby bindings needed for splits.io. So it should be somewhat easy to start using this now.

https://github.com/CryZe/livesplit-core/releases

**Comment by glacials** [comment]
Thanks, this needed an issue. Been pretty busy with life stuff for a bit but I would really like to get a chunk of free time and do this.
