### ISSUE TITLE
Resets Per Split graph shows wrong information

### ISSUE THREAD

**Issue by wooferzfg** [glacials/splits-io#278]
The graph shows the number of runs that have gotten past each segment instead of the number of runs that were reset on that segment.

For example, for http://splits.io/16hd/stats, the number of resets for Shadow Temple should be the number of segment history entries with a positive index for the previous segment (18) minus the number of entries for the current segment (16) = 2. For the first segment (Bot Boneyard), the number of resets should be the number of entries in the Run History (59) minus the number of segment history entries with a positive index for the first segment (30) = 29.

![image](https://cloud.githubusercontent.com/assets/8262173/24841597/9c7ea820-1d4d-11e7-9c0c-3f963ae625ef.png)

**Comment by BatedUrGonnaDie** [comment]
@glacials was something changed in the past that made each segments history always contain an object even if the duration_seconds is null?  I thought the history used to be just an array of times.

**Comment by glacials** [comment]
@BatedUrGonnaDie: Yeah, I believe I changed them for #271 -- an array isn't enough to associate times with specific attempts. Looks like I messed up the math when changing dependent stuff around.

**Comment by BatedUrGonnaDie** [comment]
Looks like you could close #213 then as well.

**Comment by glacials** [comment]
Aha! yeah :)
