### ISSUE TITLE
Renamed categories

### ISSUE THREAD

**Issue by emoon** [glacials/splits-io#306]
Hi,

Some of us in the Nestroid (Metroid 1) community decided to change the the names of the categories into something better. I wonder if it's possible to have the new names listed on splits.io and/or if it's possible to use some alias (add new names and point them to old or even better replace the old ones but the point to the new names)

Cheers!

**Comment by glacials** [comment]
Yep, we can do this! It's still partially a manual process on the backend, but we can assign category aliases and rename existing categories. If you can get me a list of categories you'd like to be renamed / aliased, I can set it up.

**Comment by emoon** [comment]
Hi, it seems this has been fixed already so closing this :)
