### ISSUE TITLE
API Readme JSON error

### ISSUE THREAD

**Issue by Nightfirecat** [glacials/splits-io#327]
I noticed GitHub's Markdown diff for api.md was very angry, and I found out this block is why: (starting at L145)

    ```json
    {
      "category": {
        "id": 852,
        "name": "Any%",
        "created_at": "2015-01-08T02:53:19.867Z",
        "updated_at": "2015-02-01T21:33:44.440Z"
    }
    ```

It closes the outer brace, but not the inner brace on the "category" object.

**Comment by glacials** [comment]
Nice catch! And wow yeah that diff is angry >:(
