### ISSUE TITLE
Gametime in API

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#341]
The API only returns realtime, even for runs which have gametime. It should return both, as well as the default timing for that run.

**Comment by BatedUrGonnaDie** [comment]
Would it be worth including historic information in every request now that it is all stored in posgresql and doesn't require a reparse to get that information?

**Comment by glacials** [comment]
It's probably worth revisiting. I would still be concerned about large payloads affecting response times and stability, since histories can grow so large. If we can demonstrate that the response for even the largest payload on the site returns quickly, then sure.

**Comment by BatedUrGonnaDie** [comment]
Testing locally with the largest run history that I could find (>1000 run history entries) it looks like the only slowdown is in AMS.  It takes ~13 seconds just to render the json while all the db queries take <200ms.  I looked into alternatives to AMS but it looks like we would have to drastically alter the output if we switched libraries (fast-jsonapi and jsonapi-rb).  Outside of just speed there is payload size problems where the json ends up being ~14mb with history compared to ~1.6kb with no history, but this is an extreme example.

**Comment by glacials** [comment]
Thanks for doing that analysis. You're right that it's an extreme example, but we shouldn't ignore it because of that. We can do work to support the extreme examples (like pagination), or we can put our foot down and prevent them from happening (like return an error right away if history size > n), but we should not ignore them. If we ignore them, then one day the extreme example landmine will lock up our servers and take the site down.

For v5 I'm totally fine doing something like rolling history into the run response but erroring if it's unreasonably big. That said we already use the `api-pagination` gem in some places so if it's easy to pull off pagination instead, that would be sick also.

**Comment by BatedUrGonnaDie** [comment]
If you're fine with completely changing the structure of the JSON in v5 then it might be possible to just role with it in the main responses since basically all of the time is spent with AMS.  Or you could extract all histories to their own endpoints like `/runs/xx/history` and `/runs/xx/splits/yy/history` and paginate the overall run history since split history would paginate itself.  That might just overload the server with requests though.  Look into the json-api spec if you're interested in that since all the other libraries adhere fairly strictly to that.

**Comment by BatedUrGonnaDie** [comment]
For v4 are you ok with changing the keys for the new values stored in db (`time` -> `realtime_duration_ms` & `gametime_duration_ms`), or would you rather them be converted to something in seconds like `realtime` and `gametime`?  Same question for the SoB times as well.

**Comment by glacials** [comment]
Definitely change the keys, we want ms everywhere.
