### ISSUE TITLE
Attempt number can show negative on Segment Duration Over Time graph

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#372]
![image](https://user-images.githubusercontent.com/1765799/38341268-a85302d6-3845-11e8-9fbf-ca76c1347055.png)

https://splits.io/2696/stats?timing=real

**Comment by BatedUrGonnaDie** [comment]
This unfortunately is part of the run file itself, it doesn't check to make sure that the attempt # is actually positive.  Picture of the run file included.
![sublime_text_2018-04-04_17-31-25](https://user-images.githubusercontent.com/7030913/38341559-0de309b0-382e-11e8-9e64-b42051112f5b.png)

**Comment by jhobz** [comment]
wtf is LiveSplit smoking... I never entered any times manually, so that means somehow it legitimately thought one of my attempts was attempt -4, another was attempt -5, and neither had both types of timing method.
??????

**Comment by jhobz** [comment]
Maybe a workaround for Splits I/O would be to check for any IDs that are < 0 and just set them to 0? Even if that means later ones in the file overwrite earlier ones, they were probably incorrect to begin with...

But I can see just wanting to match the file too, so feel free to close as Invalid or mark as "upstream" or something if you want.

**Comment by CryZe** [comment]
https://docs.rs/livesplit-core/0.9.0/livesplit_core/struct.SegmentHistory.html

> Stores the segment times achieved for a certain segment. Each segment is tagged with an index. Only segment times with an index larger than 0 are considered times actually achieved by the runner, while the others are artifacts of route changes and similar algorithmic changes.

**Comment by CryZe** [comment]
It's essentially an ugly old artifact that is still hanging around. We might just change it to a flag in the future.

**Comment by BatedUrGonnaDie** [comment]
Should we the just reject any history segments with a negative attempt number then, or is there a reason to leave those in the returned output?
