### ISSUE TITLE
"Recent PBs by People You Follow" section on home page does not line up with title

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#415]
![image](https://user-images.githubusercontent.com/1765799/41518571-2f0785f6-7291-11e8-91fd-63da8a1bf970.png)

All 3 of these elements should probably align together, but at the very least the title and box below should match each other.

**Comment by jhobz** [comment]
Also the bottom padding on each row in that section should probably match the top padding.

**Comment by jhobz** [comment]
The culprit for the padding appears to be a line-height value on the div surrounding the profile image.
![image](https://user-images.githubusercontent.com/1765799/41518731-043ed9fe-7292-11e8-985b-9e8a5f367945.png)

**Comment by jhobz** [comment]
Nope, I was wrong, it's a rogue `<p>` tag.
![image](https://user-images.githubusercontent.com/1765799/41518784-449a0082-7292-11e8-8cc6-b5d5c7d2ffc0.png)

**Comment by glacials** [comment]
Nice catch!
