### ISSUE TITLE
Padding-left mismatch between title content and stat callouts

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#421]
![image](https://user-images.githubusercontent.com/1765799/41756448-ad98bab8-75aa-11e8-93bd-e742c50dcdef.png)

These two sections should probably left align to the same place. The increased padding in the stats section feels off. If it were centered and/or had a background or something, then it probably would work fine with the different alignment, but as it stands it feels off imho.

**Comment by BatedUrGonnaDie** [comment]
This should be fixed with the new 2 column layout.
