### ISSUE TITLE
Timeline JS class selector matches too many elements

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [glacials/splits-io#426]
https://github.com/glacials/splits-io/blob/master/app/javascript/timeline.js#L2 selects too many elements, causing JS errors about null items since the extra elements that it selects does not have an id, which when you try to access the style property on a null reference throws an error.

To reproduce, go to any splits page, with dev console open mouse over a timeline and watch the errors throw.

**Comment by glacials** [comment]
Fixed by 4bb691cf2bd3c50f6796e74db717a90f6b4d19b5 / 0d98bf03d962bdc87e8b430735fa98eda8eb31e7 / 2407d89bb2a16732a0bd2b8dc7b0559654e41df6.
