### ISSUE TITLE
Double ad if using Back button

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#448]
Similar #439, the ad can break and duplicate itself if using the browser's back button. It should only ever be one ad.

![untitled](https://user-images.githubusercontent.com/438911/45850738-1971eb00-bcec-11e8-9150-dfb21a16cb0c.png)

**Comment by BatedUrGonnaDie** [comment]
Closed by 17b54899de8572bc16e638afeb5b82f619d3a8b6
