### ISSUE TITLE
Llanfair support

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#45]
Gnintendo gave me a decompiled Llanfair and it'd be nice to use this to get support for it.

**Comment by Nitrofski** [comment]
If this is still ongoing, you could check out the Import From Llanfair feature that was added to WSplit a while ago. I don't know if it works on all versions of Llanfair's files though, but it worked on all the files I tested.

The algorithm reads the file byte per byte and adapts itself to certain conditions like whether there is an icon or not. Even if it's not working, I think it's a good starting point.

See https://github.com/Nitrofski/WSplit/blob/master/WSplit/WSplitTimer/RunEditor.cs#L419

**Comment by BatedUrGonnaDie** [comment]
It should work pretty well since I've used it to convert my llanfair files in the past to something that other people could import easier.
