### ISSUE TITLE
Ctrl+C on dev server sometimes doesn't stop it

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#451]
Sometimes when pressing Ctrl+C to stop Docker, the process seems to quit instantly, rather than showing these lines and taking a few seconds:

<img width="356" alt="screenshot 2018-09-23 12 23 54" src="https://user-images.githubusercontent.com/438911/45932052-950dab00-bf2b-11e8-99de-8a889236f72d.png">

Afterwards, starting the server again also happens instantly, and seemingly all the log lines from the last run show up as fast as the terminal can display them. When this happens, the server hasn't actually restarted and you need to Ctrl+C again.

**Comment by BatedUrGonnaDie** [comment]
This actually happens as well after any run commands.  Using `docker-compose stop` will shut down the containers.
