### ISSUE TITLE
Watermark in exported charts

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#464]
Highcharts lets users export graphs as images. People have been doing this and uploading them to Twitter to share stuff which is great, but as a naked chart with no source it's not obvious how to make your own if you see such a tweet. Both times I've seen it, I've seen a followup tweet asking how to make one. It would be great to have something simple and unintrusive like "made @ splits.io" in a corner somewhere of the exported image, if Highcharts lets us.

**Comment by BatedUrGonnaDie** [comment]
[Credits](https://api.highcharts.com/highcharts/credits) system in highcharts.

**Comment by glacials** [comment]
Closed by 3165bf6.
