### ISSUE TITLE
If a run has no final split time, the last non-blank split is detected as the final time

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#468]
Incomplete runs uploaded with split times for some of the splits are being detected as having a final time of the last non-blank split. See https://splits.io/388v for example. This leads to incorrect detection of a user's personal best (probably among other less-visible bugs). See completed run here, not marked as Personal Best: https://splits.io/38c9 .

**Comment by glacials** [comment]
That's really odd, thanks for the report. I wonder if LiveSplit thinks this partial run was a PB.

**Comment by BatedUrGonnaDie** [comment]
Should be closed by #613
