### ISSUE TITLE
Change Effort-to-PB graph data source for playtime

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#473]
Right now the Effort-to-PB graph uses a sum of segment histories to determine playtime at the moment a PB happens, e.g. to get total playtime that happened before attempt 452, it sums all segment histories (for all segments) that had an attempt number <= 452.

When segment histories are missing because the runner changed their splits or cleared their golds, this graph is nonsensical (has a vertical line at x=0). On top of that, it feels weird that missing segment history could make a graph not having anything to do with segments flip out.

We should switch this graph over to use `(endedAt - startedAt)` from the RunHistory entries, which are not as easily accidentally reset by housekeeping. As a bonus we don't need as much effort to calculate them. These values aren't passed through to the application from our livesplit-core wrapper, which means they are not passed from the API to JavaScript when it is building the graph. We need to add support for it in these three places to depend on them.

TODO:
- [ ] Find out when startedAt / endedAt were added, so we know if we're forsaking some runs by doing this
- [ ] Switch over if above is fine

**Comment by moorecp** [comment]
The biggest issue with this that I can see is `RunHistory` doesn't store `PauseTime`, so if a runner paused their timer and run, the graph will be thrown off by that.

    <Attempt id="2" started="08/09/2019 15:30:08" isStartedSynced="True" ended="08/09/2019 21:13:00" isEndedSynced="True">
      <RealTime>01:10:50.0620000</RealTime>
      <GameTime>00:53:34.8500000</GameTime>
      <PauseTime>04:32:01.8200000</PauseTime>
    </Attempt>

It looks like the parser is sending that information back; it's just not being used. Adding it would mean that runs would need to be reparsed to add that data.

**Comment by glacials** [comment]
Nice catch! That's totally fine, we have a (rough) process for reparsing all runs. Even so, pausing is rare enough that I wouldn't worry too much about it if old runs didn't get updated swiftly or at all. In general we do want to start adding pause time to our data models though.
