### ISSUE TITLE
Double API call

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#478]
The graphs on the run page make an API call to fetch the run's history twice identically. They should be consolidated down into one.

**Comment by kenman345** [comment]
if you can point out the lines of these calls, I can try helping out. I only just stumbled on this repository from splits.io FAQ and getting some help would mean I do not need to learn the entire codebase to find the component you are concerned about here.

**Comment by glacials** [comment]
Cool, happy to help! The two calls are from these files:

```
app/javascript/graph_builder.js
app/javascript/segment_graph_builder.js
```

Each of these files fetches the run then uses functions from the individual files in `app/javascript/graphs` for calling out to the Highcharts library.

Let me know if I can help in any other way, including issues getting the repository itself up and running!

**Comment by kenman345** [comment]
No promises.

If you dont see something from me and end up getting around to this, let me know or mention me here and I'm usually quick to respond with where I might be at.

**Comment by BatedUrGonnaDie** [comment]
@kenman345 Just letting you know I took care of this.

**Comment by kenman345** [comment]
Yea thanks, I’m going to review that code so I learn.

**Comment by BatedUrGonnaDie** [comment]
If you have any questions about it feel free to ask, I'm sure one of us can help walk you through anything you need help with.
