### ISSUE TITLE
404 on category link from splits [Bug]

### ISSUE THREAD

**Issue by lepelog** [glacials/splits-io#494]
Recreate this bug: [https://splits.io/3i6t](https://splits.io/3i6t) , then click on the Category "Trial of the Sword". Usually this should redirect to a leaderboard with all the splits, but instead I get a 404 error. Also last time I checked the Breath of the Wild page there were a lot more categories.
Also if you search for "breath of the wild", there are 2 games, one with 17 and one with 51 categories, but they link both to the same url, that might be related to the issue

**Comment by moorecp** [comment]
@glacials This issue seems fixed. Clicking the category works as expected and only 1 game with 82 categories shows up when searched.
