### ISSUE TITLE
Seeking video via timeline isn't working

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#500]
I went to check out the navigating-via-timeline feature after reading #499 because I didn't know it existed. Unfortunately, I don't think it's working properly, at least not for Twitch highlights. Clicking on the timeline on https://splits.io/397v clearly tries to seek the VOD, but it just resets it to the beginning.

**Comment by glacials** [comment]
Hmm, nice catch! I feel like I'm going crazy -- I remember this `start_ms` being converted automatically into `startMs` for the JavaScript world, and I remember this working in production! Maybe updating some library somewhere removed that behavior.
