### ISSUE TITLE
Split graphs sometimes don't adjust size correctly

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#504]
This might be one bug or two.

(EDIT: First bug is fixed!) First, sometimes the "segment duration over time" graph is about half-width compared to the container. This can happen even if the window is never resized, and has been seen happening after collapsing then re-expanding a segment. For a video see the Discord server's #bugs channel, 2019-02-11 09:37 AM PST, recorded on Windows 8.1 64-bit with Firefox 65.0.
![unknown](https://user-images.githubusercontent.com/438911/52582009-0d90dd80-2de1-11e9-947b-4ddd165576a8.png)

Second, if you expand a graph, widen the browser window (causing the graph to widen with it), then shrink the browser window, the graph doesn't reshrink with it and you're left with the left side of the page being horizontally scrollable because of the extra width:
![screen shot 2019-02-11 at 09 40 42](https://user-images.githubusercontent.com/438911/52582251-9d368c00-2de1-11e9-8f82-4c7a4129f2e2.png)

**Comment by BatedUrGonnaDie** [comment]
This should be fixed with #506 being merged.

**Comment by glacials** [comment]
Looks like the first half is fixed but not the second half, so they were unrelated after all. Re-opening just to dedicate to the second bug mentioned.
