### ISSUE TITLE
Default "Route only" to unchecked if you own the run

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#543]
We often have issues with people accidentally effectively clearing their history by restoring from a splits.io backup without unchecking "Route only" before exporting. If you're exporting your own splits, chances are it's to restore from backup, so we should default this to unchecked if you own the run.

**Comment by BatedUrGonnaDie** [comment]
Closed with 05ff903f5cc8f05049b56edfdf1ae135d92a0dce
