### ISSUE TITLE
(local dev) Auto-populate OAuth self-client

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#564]
For the site to use its own APIs, it needs its own client ID and secret in environment variables (in `.envrc`). This means that to start developing you need to `make build run` (~10 min), upload a run to make the settings page not error, go to the settings page and make a client with the correct redirect URI, copy the client ID and secret into `.envrc`, then `make build run` again (~10 min).

Rather than require all this, maybe we can hardcode the client ID and client secret env vars for local dev and have them get put into the database through seeding or something, so it's ready-to-use after the first `make build run`.

**Comment by BatedUrGonnaDie** [comment]
Believe this was closed by afbeb694d67f0a1c0f5222f40746bd638495eb80
