### ISSUE TITLE
Error after using make command

### ISSUE THREAD

**Issue by MilesBradt** [glacials/splits-io#576]
Unsure if it's on my end or not since I'm new to docker, running this on linux mint 19 cinnamon v3.8.8

I don't even know how to explain it but I documented the error as well as what was working correctly before the error happened. Just a warning, it's a lot. 

https://docs.google.com/document/d/1yqpQwHQN66mR7PMKmQ2NXmiRjfSJr_7EUvSsiGQmEHI/edit?usp=sharing

**Comment by BatedUrGonnaDie** [comment]
It looks like it ran the linter.  You should be able to ignore all those, just make sure that `make build` returns successfully, and if it does then `make run` will spin the server up at `localhost:3000/`

**Comment by MilesBradt** [comment]
got it, thanks!

**Comment by glacials** [comment]
We'll keep this open as a "typing `make` as a new developer should generally work and if not should not be super hard to understand what's going wrong and why" issue ;)
