### ISSUE TITLE
Splits without names don't get processed correctly

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#587]
Any split with a blank name (`""`) doesn't get added to the database correctly, causing a 500 for runs where all splits have blank names, and an incomplete run page for runs where some splits have blank names (as the splits don't exist).

Example of run with all blank names, causing a 500: https://splits.io/4ild/export/livesplit
Example of run with some blank names, causing an incomplete run page: https://splits.io/4ilc

**Comment by BatedUrGonnaDie** [comment]
Closed by #613
