### ISSUE TITLE
Runs misattributed to other runners?

### ISSUE THREAD

**Issue by Nightfirecat** [glacials/splits-io#59]
Upon logging in recently, I found [that I evidently have some new runs](http://i.imgur.com/FIbCQcF.png) (OoT and Minish Cap). I've never run these games, nor do I have splits online or locally.

Attempting to visit the links ([OoT](http://splits.io/BJcj) and [Minish Cap](http://splits.io/9h-H) respectively) gives me a 500 error.

**Comment by glacials** [comment]
No known reproduces since opening, so closing this.
