### ISSUE TITLE
Skipping a split makes comparison aligns off

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#619]
When you skip a split, we roll it into the following segment for display purposes, renaming it `"<segment1-name> + <segment2-name>"`.

Now that we have comparisons lining up to each other, an existing issue comes to light where one timeline thinks its splits are one ahead of the other's.

See an example here: https://splits.io/4nqv?compare=4nch
- The top timeline skipped "Darkness 60 Mats", the 9th split
- Therefore hovering over any segment after that one, in either timeline, causes the other timeline to align to the wrong split

This also exposes itself in having the split colors be off from each other.

**Comment by moorecp** [comment]
I was giving thought today to modifying it to align on split name first, if possible, then on split number as a fallback. I added a bunch of splits to my own runs and it makes the entire feature useless to me.

Without looking into it, I think that would fix this issue, as well. I'm actually thinking the feature might need some revisiting as it is. If the number of splits is fairly different, it's of potentially dubious value and distracting.

**Comment by moorecp** [comment]
This GIF exhibits the edge case I was referring to with my edit above. In this situation (due to not having subsplit code), there are not fuzzy matches for the 4th split I mouseover. So, the first 3 line up with their fuzzilied-named companions, but there is no good enough match for the 4th, so the fallback is segment number, which causes the other timeline to snap way back due to the large disparity in number of segments between the 2 runs. After that, the 5th split does have a fuzzy match, so it snaps things forward again.

![fuzzy_matching](https://user-images.githubusercontent.com/293433/65978360-924c6c80-e441-11e9-8d7b-a6889c1d7101.gif)

**Comment by glacials** [comment]
Do you think fuzzy matching would provide enough value otherwise for that downside to be worth it vs. fixing it in a more naive way like adding skipped splits into the timeline as 0-width?

**Comment by moorecp** [comment]
I think in the case of skipped splits, it'll work great. The bigger problem is in comparing runs with some splits that will match by name and others that won't, so the case of 2 different users with differently named splits, additional splits, or just straight up different splits.

**Comment by moorecp** [comment]
In thinking about this more, I guess I'm not sure how people commonly use the comparison feature. I'm not sure how many people have the same splits as the run they're comparing against. Maybe it's a lot or maybe it's very few. The few ideas I've had on this are:

- Always use segment number (the current state of the world)
- Always use fuzzy-matching segment name and just don't move the timelines if there is no match
- Use fuzzy-matching segment name, then fall back to segment number as seen in https://github.com/glacials/splits-io/issues/619#issuecomment-537104625
- Use fuzzy-matching segment name if some threshold is met for matching segments and just don't move timeline when there is no match. If the threshold isn't met, use segment numbers. These matches would probably need to be precomputed.
- Precompute segment matches. Use fuzzy-matching where possible and then use relative segment numbers when between segments that were fuzzy matched. In the GIF in https://github.com/glacials/splits-io/issues/619#issuecomment-537104625, it would pick a segment between those matched for `Phantoon` and `Botwoon` when mousing-over `Gravity Suit`. That would prevent timelines from snapping all over the place and move it forward/back in a reasonable fashion. This is also the most complicated solution.

**Comment by BatedUrGonnaDie** [comment]
Personally I'm a fan of use segment # always if they have the same # of segments.  If they don't then use fuzzy matching on names with a threshold and if nothing passes the threshold then do nothing.

**Comment by moorecp** [comment]
That sounds pretty good. In your second scenario where you're using fuzzy-matching, what do you do on segments without a match? I'm guessing just hold the timelines in place until you mouseout from the timeline or mouseover a segment with a match?

**Comment by BatedUrGonnaDie** [comment]
Just have them stay in their original position as if you were not hovering over anything on the timeline.

**Comment by moorecp** [comment]
I guess my question was more along the lines of the example in https://github.com/glacials/splits-io/issues/619#issuecomment-537104625. If you're already over a matched segment, then hit an unmatched segment, should the timelines snap back to their origins or just stay where they are?

**Comment by BatedUrGonnaDie** [comment]
In my opinion in that scenario the best way to handle would be transition back to its default location and show a small bubble/warning saying no matching segment found.  That way the user knows something went wrong with the match and not that the page is just broken, but also isn't getting garbage compares.
