### ISSUE TITLE
Chart titles use different font families

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#621]
Honestly not sure what's causing this, but different charts are using different fonts for their titles, despite being passed in the same way:

<img width="808" alt="Screen Shot 2019-10-03 at 11 06 35" src="https://user-images.githubusercontent.com/438911/66152219-e6845780-e5cd-11e9-8163-03c6465987da.png">

**Comment by jhobz** [comment]
Hmm... I'm seeing the same font for both, but I notice the primary font is Helvetica Neue, which my computer wouldn't have as it's not a Mac. This could be an OS-specific problem. Are you using a Mac? And which browser? CSS is my jam so I can try to look into this a little bit.

**Comment by jhobz** [comment]
For reference, here's what I see on Win 10, Chrome.

![image](https://user-images.githubusercontent.com/1765799/66164269-472c8800-e600-11e9-8408-239dcc162cc6.png)

**Comment by glacials** [comment]
Yeah I'm using Chrome on macOS.

**Comment by moorecp** [comment]
Yeah, the first chart is using the fonts as specified by the theme that is set. All following charts are using default settings. At least, that's what I'm seeing. The question is why is what is being set in the theme being ignored after the first chart?
