### ISSUE TITLE
Global game lists cause lag

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#662]
With #660 having added basically every speedrun.com game to the site, the places where we display every game are getting v. slow: the run edit page, the race edit section, and the games index (`/games`). We should convert these all into something that scales better with the number of games, like an autocomplete like the global search bar has.

**Comment by BatedUrGonnaDie** [comment]
I believe this is fixed by 3bd404b67ffbe2f4ae34c71d5b172cff3ff8c0ee

CC @glacials
