### ISSUE TITLE
Game shortnames with periods 500

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#664]
Games with periods in their shortnames cause a 500 error when accessing their game page, e.g. https://splits.io/games/tron2.0, presumably because Rails is treating the `.` as an extension (so it's asking for the game `tron2` in the format `0`).

**Comment by BatedUrGonnaDie** [comment]
Fixed by 3bd404b67ffbe2f4ae34c71d5b172cff3ff8c0ee
