### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#67]
You should be able to upload blank splits and somehow declare that they represent a route for that category. Then, the category page could display all routes. And we could choose to display information only relevant to the route on the route page, instead of things having to do specifically with a run (stats, timeline, etc.).

See #190 for related info and for a feature that this would enable.

This feature would
1. help people new to a category discover blank splits separately from discovering actual splits,
2. make it easier for people who want to standardize their splits to do so, and as a side effect would
3. help LiveSplit comparisons work among more people.

**Comment by glacials** [comment]
An alternative to this is to not supply blank splits, and instead create a branded concept of "routes" where you upload blank splits and somehow declare that they represent a route for that category. Then, the category page could display all routes. This would make standardizing on a set of splits easier for those who want to do it. And we could choose to display information only relevant to the route on the route page, instead of things having to do specifically with a run (stats, timeline, etc.).

See #190 for related info and for a feature that this would enable.

**Comment by glacials** [comment]
I'm going to rename this issue to Routes because I like that idea better than "download clean splits", and the two achieve the same goal.

Also it's important to point out that even with identical splits, because of differences between runners there are no guarantees that what an automated system thinks is a theoretical perfect run is actually attainable for all games. There's no way to know that the runners split at the same moment between levels, meaning that the first and last splits of the supposed theoretical perfect run could be artificially short.

For example, in Super Mario Sunshine, pretty much everyone splits when you get a shine. But the "shine get" cutscene is about 4 seconds long. Some people split when the cutscene starts, some people split when the shine counter goes up, some people split when the cutscene ends. So if you split when the cutscene starts, your very first segment is shorter by 4 seconds than that of a person who splits when the jingle ends, assuming equal skill. And if the game happened to end in the same fashion, that person's last split would be shorter than yours by 4 seconds. So now the supposed theoretical perfect run is 8 seconds faster than what's actually achievable.

I don't think this is a particularly huge deal, but probably worth adding a user-visible note about when this becomes a feature.

**Comment by Lighnat0r** [comment]
Routes would also be a really nice feature to be able to show them on game's resource pages on [speedrun.com](http://speedrun.com)

**Comment by glacials** [comment]
:+1:
