### ISSUE TITLE
/api/v4/runner always gives 403

### ISSUE THREAD

**Issue by bgreenacre** [glacials/splits-io#703]
Trying to call the `/api/v4/runner` with fetch js function. I'm sending my oauth token in the `Authorization: Bearer <token>` header so I should get the current runner that's is attached to that token no? Am I missing something else?

**Comment by glacials** [comment]
I've just tested it manually and it seems to work for me. Can you confirm that your token is valid by sending a request like so?
```http
GET https://splits.io/oauth/token/info?access_token=YOUR_TOKEN_HERE
```
If it's invalid but you don't know why, make sure you are using an access token, not a code.

**Comment by bgreenacre** [comment]
The token I am using is valid. I get a 200 response with a json payload.

**Comment by bgreenacre** [comment]
I was missing a client scope when getting a oauth token. I can now get my runner using my token from /api/v4/runner using postman. However, my call using fetch is failing on the cors call apparently and I have mode set to cors.

**Comment by bgreenacre** [comment]
It seems the `/api/v4/runner` does NOT send back any CORS headers when the OPTIONS request has the value `authorization` in the header `Access-Control-Request-Headers`. This is causing all my requests with fetch to be blocked. I've confirmed this using postman too. Please take a look at my screencap of postman.

![splits-io-options-example](https://user-images.githubusercontent.com/167656/85770548-a6777e80-b6e0-11ea-97cc-c3d00524f31d.png)

**Comment by glacials** [comment]
Thanks for the detailed report. I've just pushed a fix, can you try it out now?

**Comment by bgreenacre** [comment]
It sure does work! Thanks!
