### ISSUE TITLE
Can't access `Link` header in response using CORs fetch request in JS

### ISSUE THREAD

**Issue by bgreenacre** [glacials/splits-io#705]
When using fetch with a js site (therefore CORs) all of the special headers are inaccessible in the response object (ie. Link). In order to make them accessible the OPTIONS response header `access-control-expose-headers` needs to contain a complete list of what response headers fetch can make accessible. [This stackoverflow answer has more details](https://stackoverflow.com/a/44816592)

**Comment by glacials** [comment]
Did this commit fix this issue for you? b714cf5e659d947e8e55b64dd6ec7179f5d7d046

If not I'm open to accepting a PR for this.

**Comment by bgreenacre** [comment]
Nope. I'll try and make a PR this weekend.

**Comment by bgreenacre** [comment]
I just left a comment on your cited commit. Basically `expose` should be set to `*`.
