### ISSUE TITLE
Videos wonky after pressing back button

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#710]
"when going back to a run page via the back button, the seek via click on the splits bar doesn't work"

Reported from this Discord message: https://discordapp.com/channels/361957211318124555/535862834261655593/733219640796381216

**Comment by moorecp** [comment]
I've moved all the player code into the `onReady`, but the same issue still exists due to Turbolinks. I'm working on trying to change how the YouTube stuff works with regard to Turbolinks. If I can figure something out here, it might help with the janky fix to #707.
