### ISSUE TITLE
Authorization URL does not support Google login

### ISSUE THREAD

**Issue by MichaelJBerk** [glacials/splits-io#721]
The URL for granting access to a third-party application (https://splits.io/oauth/authorize) redirects the user to the Twitch login page, if they are not already signed in to Splits.io. If a user uses their Google account to log in (and does not have a Twitch account connected), then they will not be able to grant access to a third-party application unless they have already logged in to Splits.io.

It would be best if the auth URL took a logged-out use to a page giving them the choice for how to sign in.

**Comment by glacials** [comment]
I agree, I think this is an artifact from a time we only supported Twitch. I think our current sign in modal could just be extracted to a partial and reused in a page. I'd gladly accept a PR for this, otherwise I can get around to it eventually. Thanks for the report!
